// 
// Code auto generated by GuiXml.
// 

using System;
using Zene.Structs;
using Zene.Graphics;
using Zene.Windowing;
using Zene.GUI;

namespace Sorting
{
    internal static class test
    {
        internal static void LoadGUI(ElementList el, Program program)
        {
            IElement root = el.Source;
            
            Container container1 = new Container();
            container1.Layout = new Layout(0f, 0.9f, 2f, 0.2f);
            container1.LayoutManager = new XSpacerLayout();
            Slider slider1 = new Slider();
            slider1.Id = @"MaxValue";
            slider1.Position = new Vector2(-0.65, 0.75);
            slider1.Padding = new Vector2(10, 30);
            slider1.SilderWidth = 150f;
            slider1.Value = 100f;
            container1.Children.Add(slider1);
            
            Button button1 = new Button();
            button1.Layout = new TextLayout(10f, 10f, -0.25f, 0.75f, 0f, 0f, true);
            button1.BorderWidth = 2f;
            button1.CornerRadius = 0.2f;
            button1.TextSize = 17f;
            button1.Click += program.BubbleSortButton;
            button1.Text = @"Bubble Sort";
            container1.Children.Add(button1);
            
            EnterBox enterbox1 = new EnterBox();
            enterbox1.Layout = new TextLayout(5f, 5f, 0f, 0.75f, 0.15f, 0f, true);
            enterbox1.BorderWidth = 2f;
            enterbox1.CornerRadius = 0.1f;
            enterbox1.TextSize = 17f;
            enterbox1.TextEntered += program.OnTextInput;
            container1.Children.Add(enterbox1);
            
            Button button2 = new Button();
            button2.Layout = new TextLayout(10f, 10f, 0.25f, 0.75f, 0f, 0f, true);
            button2.BorderWidth = 2f;
            button2.CornerRadius = 0.2f;
            button2.TextSize = 17f;
            button2.Click += program.InsertionSortButton;
            button2.Text = @"Insertion Sort";
            container1.Children.Add(button2);
            
            Button button3 = new Button();
            button3.Layout = new TextLayout(10f, 10f, 0.65f, 0.75f, 0f, 0f, true);
            button3.BorderWidth = 2f;
            button3.CornerRadius = 0.2f;
            button3.TextSize = 17f;
            button3.Click += program.Randomise;
            button3.Text = @"Randomise";
            container1.Children.Add(button3);
            
            el.Add(container1);
            
            BarContainer barcontainer1 = new BarContainer();
            barcontainer1.Id = @"MainContainer";
            barcontainer1.Layout = new Layout(0f, 0f, 1.5f, 1.5f);
            barcontainer1.Colour = new ColourF(0.3f, 0.3f, 0.3f);
            Bar bar1 = new Bar();
            bar1.Value = 50f;
            barcontainer1.Children.Add(bar1);
            
            Bar bar2 = new Bar();
            bar2.Value = 20f;
            barcontainer1.Children.Add(bar2);
            
            Bar bar3 = new Bar();
            bar3.Value = 70f;
            barcontainer1.Children.Add(bar3);
            
            Bar bar4 = new Bar();
            bar4.Value = 10f;
            barcontainer1.Children.Add(bar4);
            
            Bar bar5 = new Bar();
            bar5.Value = 80f;
            barcontainer1.Children.Add(bar5);
            
            Bar bar6 = new Bar();
            bar6.Value = 90f;
            barcontainer1.Children.Add(bar6);
            
            Bar bar7 = new Bar();
            bar7.Value = 45f;
            barcontainer1.Children.Add(bar7);
            
            Bar bar8 = new Bar();
            bar8.Value = 72f;
            barcontainer1.Children.Add(bar8);
            
            el.Add(barcontainer1);
            
        }
    }
}